"""Add created_at column

Revision ID: 1c4b2302e22f
Revises: 301b61bdcaf1
Create Date: 2024-02-16 21:05:58.075658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4b2302e22f'
down_revision = '301b61bdcaf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
